name: update repo

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: get latest hugo version
        run: echo ::set-env name=HUGO_LATEST_VERSION::$(curl -s https://github.com/gohugoio/hugo/releases.atom | grep -oPm1 "(?<=<title>v)[^<]+")
      - name: print latest version
        run: echo $HUGO_LATEST_VERSION
      - name: latest tag
        run: echo ::set-env name=LATEST_TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: print latest tag
        run: echo $LATEST_TAG_VERSION
